# Generated by Django 5.2.11 on 2026-02-25 05:37

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('juntagrico_custom_sub', '0001_initial'), ('juntagrico_custom_sub', '0002_auto_20190317_1604'), ('juntagrico_custom_sub', '0003_auto_20190815_2036'), ('juntagrico_custom_sub', '0004_auto_20191005_1144'), ('juntagrico_custom_sub', '0005_customdelivery_delivery_comment'), ('juntagrico_custom_sub', '0006_auto_20191113_2304'), ('juntagrico_custom_sub', '0007_csdepot'), ('juntagrico_custom_sub', '0008_auto_20191209_2003'), ('juntagrico_custom_sub', '0009_product_code'), ('juntagrico_custom_sub', '0010_generate_code'), ('juntagrico_custom_sub', '0011_enforce_constraints'), ('juntagrico_custom_sub', '0012_alter_subscriptioncontent_subscription'), ('juntagrico_custom_sub', '0013_alter_subscriptionsizemandatoryproducts_unique_together_and_more')]

    initial = True

    dependencies = [
        ('juntagrico', '0051_tour_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Lieferdatum')),
                ('delivery_comment', models.TextField(blank=True, default='', verbose_name='Mitteilung')),
            ],
            options={
                'verbose_name': 'Lieferung',
                'verbose_name_plural': 'Lieferungen',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('units', models.FloatField(default=0, verbose_name='Grösse')),
                ('unit_multiplier', models.IntegerField(default=1, verbose_name='Grössen multiplikator')),
                ('unit_name', models.CharField(default='', max_length=100, verbose_name='Name Grösse')),
                ('user_editable', models.BooleanField(default=True, verbose_name='Menge durch Nutzer veränderbar')),
                ('code', models.CharField(default='1', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Sortier-Code')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.CreateModel(
            name='CsDepot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('juntagrico.depot',),
        ),
        migrations.CreateModel(
            name='CustomDeliveryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='juntagrico_custom_sub.customdelivery', verbose_name='Lieferung')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico_custom_sub.product', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Lieferobjekt',
                'verbose_name_plural': 'Lieferobjekte',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBundleMandatoryProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico_custom_sub.product')),
                ('subscription_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.subscriptionbundle')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='mandatory_for_bundles',
            field=models.ManyToManyField(related_name='mandatory_products', through='juntagrico_custom_sub.SubscriptionBundleMandatoryProducts', to='juntagrico.subscriptionbundle'),
        ),
        migrations.CreateModel(
            name='SubscriptionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='juntagrico.subscription')),
            ],
            options={
                'verbose_name': 'Abo Inhalt',
                'verbose_name_plural': 'Abo Inhalte',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionContentFutureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico_custom_sub.product')),
                ('subscription_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_products', to='juntagrico_custom_sub.subscriptioncontent')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico_custom_sub.product')),
                ('subscription_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='juntagrico_custom_sub.subscriptioncontent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscriptionbundlemandatoryproducts',
            constraint=models.UniqueConstraint(fields=('subscription_bundle', 'product'), name='unique_subscription_bundle_product'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncontentfutureitem',
            unique_together={('subscription_content', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncontentitem',
            unique_together={('subscription_content', 'product')},
        ),
    ]
