# Generated by Django 2.1.3 on 2019-03-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('juntagrico_custom_sub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionContentFutureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionSizeMandatoryProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptioncontent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscriptioncontent',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='user_editable',
            field=models.BooleanField(default=True, verbose_name='Menge durch Nutzer veränderbar'),
        ),
        migrations.AlterField(
            model_name='subscriptioncontent',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content',
                                       to='juntagrico.Subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionsizemandatoryproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico_custom_sub.Product'),
        ),
        migrations.AddField(
            model_name='subscriptionsizemandatoryproducts',
            name='subscription_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.SubscriptionSize'),
        ),
        migrations.AddField(
            model_name='subscriptioncontentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico_custom_sub.Product'),
        ),
        migrations.AddField(
            model_name='subscriptioncontentitem',
            name='subscription_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                    to='juntagrico_custom_sub.SubscriptionContent'),
        ),
        migrations.AddField(
            model_name='subscriptioncontentfutureitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico_custom_sub.Product'),
        ),
        migrations.AddField(
            model_name='subscriptioncontentfutureitem',
            name='subscription_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_products',
                                    to='juntagrico_custom_sub.SubscriptionContent'),
        ),
        migrations.AddField(
            model_name='product',
            name='mandatory_for_sizes',
            field=models.ManyToManyField(related_name='mandatory_products',
                                         through='juntagrico_custom_sub.SubscriptionSizeMandatoryProducts',
                                         to='juntagrico.SubscriptionSize'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncontentitem',
            unique_together={('subscription_content', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncontentfutureitem',
            unique_together={('subscription_content', 'product')},
        ),
    ]
