# Generated by Django 2.1.3 on 2019-02-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('juntagrico_custom_sub', '0002_subscriptioncontentfutureitem_subscriptioncontentitem'), ('juntagrico_custom_sub', '0003_auto_20190210_1637'), ('juntagrico_custom_sub', '0004_auto_20190210_1704'), ('juntagrico_custom_sub', '0005_auto_20190210_1704'), ('juntagrico_custom_sub', '0006_auto_20190210_1718')]

    dependencies = [
        ('juntagrico_custom_sub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionContentFutureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico_custom_sub.Product')),
                ('subscription_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_contents', to='juntagrico_custom_sub.SubscriptionContent')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juntagrico_custom_sub.Product')),
                ('subscription_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='juntagrico_custom_sub.SubscriptionContent')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptioncontent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscriptioncontent',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncontentfutureitem',
            unique_together={('subscription_content', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncontentitem',
            unique_together={('subscription_content', 'product')},
        ),
        migrations.AlterField(
            model_name='subscriptioncontent',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='juntagrico.Subscription'),
        ),
    ]
