# Generated by Django 2.2.2 on 2019-08-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('juntagrico_custom_sub', '0002_auto_20190317_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Lieferdatum')),
            ],
            options={
                'verbose_name': 'Lieferung',
                'verbose_name_plural': 'Lieferungen',
            },
        ),
        migrations.CreateModel(
            name='CustomDeliveryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Kommentar')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                               to='juntagrico_custom_sub.CustomDelivery', verbose_name='Lieferung')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico_custom_sub.Product',
                                   verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Lieferobjekt',
                'verbose_name_plural': 'Lieferobjekte',
                'unique_together': {('product', 'delivery')},
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AlterModelOptions(
            name='subscriptioncontent',
            options={'verbose_name': 'Abo Inhalt', 'verbose_name_plural': 'Abo Inhalte'},
        ),
    ]
