# Generated by Django 2.2.4 on 2019-10-05 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('juntagrico', '0017_auto_20190625_1013'),
        ('juntagrico_custom_sub', '0003_auto_20190815_2036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionsizemandatoryproducts',
            unique_together={('subscription_size', 'product')},
        ),
    ]
