# Generated by Django 2.2.4 on 2019-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('juntagrico_custom_sub', '0004_auto_20191005_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdelivery',
            name='delivery_comment',
            field=models.TextField(default='', verbose_name='Kommentar'),
        ),
    ]
