# Generated by Django 2.2.4 on 2019-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('juntagrico_custom_sub', '0005_customdelivery_delivery_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdeliveryproduct',
            name='comment',
        ),
        migrations.AlterField(
            model_name='customdelivery',
            name='delivery_comment',
            field=models.TextField(blank=True, default='', verbose_name='Mitteilung'),
        ),
    ]
