# Generated by Django 2.2.4 on 2019-11-16 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('juntagrico', '0018_auto_20191019_2031'),
        ('juntagrico_custom_sub', '0006_auto_20191113_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsDepot',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('juntagrico.depot',),
        ),
    ]
