# Generated by Django 2.2.6 on 2019-12-09 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('juntagrico_custom_sub', '0007_csdepot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customdeliveryproduct',
            unique_together=set(),
        ),
    ]
