# Generated by Django 4.2.18 on 2025-04-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0041_1_7'),
        ('juntagrico_custom_sub', '0011_enforce_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncontent',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='juntagrico.subscription'),
        ),
    ]
