# Generated by Django 5.2.11 on 2026-02-25 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0051_tour_weekday'),
        ('juntagrico_custom_sub', '0012_alter_subscriptioncontent_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionsizemandatoryproducts',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='mandatory_for_sizes',
            field=models.ManyToManyField(related_name='mandatory_products', through='juntagrico_custom_sub.SubscriptionSizeMandatoryProducts', to='juntagrico.subscriptionbundle'),
        ),
        migrations.AlterField(
            model_name='subscriptionsizemandatoryproducts',
            name='subscription_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.subscriptionbundle'),
        ),
        migrations.RenameModel(
            old_name='SubscriptionSizeMandatoryProducts',
            new_name='SubscriptionBundleMandatoryProducts',
        ),
        migrations.RenameField(
            model_name='subscriptionbundlemandatoryproducts',
            old_name='subscription_size',
            new_name='subscription_bundle',
        ),
        migrations.AddConstraint(
            model_name='subscriptionbundlemandatoryproducts',
            constraint=models.UniqueConstraint(fields=('subscription_bundle', 'product'),
                                               name='unique_subscription_bundle_product'),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mandatory_for_sizes',
            new_name='mandatory_for_bundles',
        ),
    ]
