# Generated by Django 5.2.10 on 2026-01-25 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico', '0050_post_743'),
        ('juntagrico_custom_sub', '0012_alter_subscriptioncontent_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mandatory_for_sizes',
            field=models.ManyToManyField(related_name='mandatory_products', through='juntagrico_custom_sub.SubscriptionSizeMandatoryProducts', to='juntagrico.productsize'),
        ),
        migrations.AlterField(
            model_name='subscriptionsizemandatoryproducts',
            name='subscription_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juntagrico.productsize'),
        ),
    ]
